// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelOrderFinal.Models
{
    public partial class Activity
    {
        public Activity()
        {
            Order = new HashSet<Order>();
        }

        public int ActivityId { get; set; }
        public string ActivityName { get; set; }
        public string ActivityImage { get; set; }
        public string ActivityDirections { get; set; }
        public DateTime? ActivityTime { get; set; }
        public string ActivityPlace { get; set; }
        public int? ActivityPeople { get; set; }
        public string ActivityCost { get; set; }

        public virtual ICollection<Order> Order { get; set; }
    }
}