// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelOrderFinal.Models
{
    public partial class Admin
    {
        public string AdminId { get; set; }
        public string AdminAccount { get; set; }
        public string AdminPassword { get; set; }
    }
}