// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace HotelOrderFinal.Models
{
    public partial class Comment
    {
        public int CommentId { get; set; }
        [DisplayName("評點日期")]
        public DateTime? CommentDate { get; set; }
        [DisplayName("會員編號")]
        public string MemberId { get; set; }
        [DisplayName("分　類")]
        public int? CommentClass { get; set; }
        [DisplayName("評　　　　　　　點")]
        public int? CommentPoint { get; set; }
        [DisplayName("評論摘要")]
        public string CommentDetail { get; set; }

        public virtual RoomMember Member { get; set; }
    }
}