// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelOrderFinal.Models
{
    public partial class Discount
    {
        public Discount()
        {
            Order = new HashSet<Order>();
        }

        public int DiscountId { get; set; }
        public string DiscountName { get; set; }
        public byte[] DiscountImage { get; set; }
        public string DiscountDirections { get; set; }
        public DateTime? DiscountStart { get; set; }
        public DateTime? DiscountEnd { get; set; }
        public decimal? DiscountDiscount { get; set; }
        public string MemberId { get; set; }
        public int? DiscountUse { get; set; }

        public virtual RoomMember Member { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}