// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelOrderFinal.Models
{
    public partial class DiscountDetail
    {
        public int DiscountDetailId { get; set; }
        public string MemberId { get; set; }
        public int? DiscountId { get; set; }
        public DateTime? DiscountStart { get; set; }
        public DateTime? DiscountEnd { get; set; }
        public int? DiscountUse { get; set; }

        public virtual Discount Discount { get; set; }
        public virtual RoomMember Member { get; set; }
    }
}