// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelOrderFinal.Models
{
    public partial class HotelFacility
    {
        public HotelFacility()
        {
            MultipleHotelFacility = new HashSet<MultipleHotelFacility>();
        }

        public int HotelFacilityId { get; set; }
        public string HotelFacilityName { get; set; }
        public string HotelFacilityImage { get; set; }

        public virtual ICollection<MultipleHotelFacility> MultipleHotelFacility { get; set; }
    }
}