// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelOrderFinal.Models
{
    public partial class HotelIndustry
    {
        public HotelIndustry()
        {
            MultipleHotelFacility = new HashSet<MultipleHotelFacility>();
            Room = new HashSet<Room>();
        }

        public int HotelId { get; set; }
        public string HotelName { get; set; }
        public string HotelPhone { get; set; }
        public int? HotelRegionId { get; set; }
        public string HotelAddress { get; set; }
        public string HotelImage { get; set; }
        public string HotelImageDiscription { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }

        public virtual HotelRegionName HotelRegion { get; set; }
        public virtual ICollection<MultipleHotelFacility> MultipleHotelFacility { get; set; }
        public virtual ICollection<Room> Room { get; set; }
    }
}