// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelOrderFinal.Models
{
    public partial class MultipleRoomFacility
    {
        public int MultipleRoomFacilitiyId { get; set; }
        public string RoomId { get; set; }
        public int? FacilityId { get; set; }

        public virtual RoomFacility Facility { get; set; }
        public virtual Room Room { get; set; }
    }
}