// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelOrderFinal.Models
{
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            OrderSpecialRequest = new HashSet<OrderSpecialRequest>();
        }

        public string OrderDetailId { get; set; }
        public string OrderId { get; set; }
        public DateTime? CheckInDate { get; set; }
        public DateTime? CheckOutDate { get; set; }
        public DateTime? PaymentDate { get; set; }
        public int? PaymentId { get; set; }
        public decimal? PaymentPrice { get; set; }
        public int? OrderDetailStatusId { get; set; }
        public string RoomId { get; set; }
        public string OrderDetailRemark { get; set; }

        public virtual Order Order { get; set; }
        public virtual OrderDetailStatus OrderDetailStatus { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual ICollection<OrderSpecialRequest> OrderSpecialRequest { get; set; }
    }
}