// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelOrderFinal.Models
{
    public partial class Order
    {
        public Order()
        {
            OrderDetail = new HashSet<OrderDetail>();
        }

        public string OrderId { get; set; }
        public string MemberId { get; set; }
        public DateTime OrderDate { get; set; }
        public decimal? OrderTotalPrice { get; set; }
        public int? CheckInPeople { get; set; }
        public string OrderRemark { get; set; }
        public string OrderStatus { get; set; }
        public int? ActivityId { get; set; }
        public int? DiscountId { get; set; }
        public int? ActivityPeople { get; set; }

        public virtual Activity Activity { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual RoomMember Member { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}