// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace HotelOrderFinal.Models
{
    public partial class Order
    {
        public Order()
        {
            OrderDetail = new HashSet<OrderDetail>();
        }

        [DisplayName("訂單ID")]
        public string OrderId { get; set; }
        [DisplayName("會員ID")]
        public string MemberId { get; set; }
        [DisplayName("訂單日期")]
        public  DateTime OrderDate { get; set; }
        [DisplayName("訂單金額")]
        public decimal? OrderTotalPrice { get; set; }
        [DisplayName("訂單人")]
        public int? CheckInPeople { get; set; }
        [DisplayName("備註")]
        public string OrderRemark { get; set; }
        public string OrderStatus { get; set; }
        public int? ActivityId { get; set; }
        public int? DiscountId { get; set; }
        public int? ActivityPeople { get; set; }

        public virtual Activity Activity { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual RoomMember Member { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}