// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelOrderFinal.Models
{
    public partial class OrderDetailStatus
    {
        public OrderDetailStatus()
        {
            OrderDetail = new HashSet<OrderDetail>();
        }

        public int OrderDetailStatusId { get; set; }
        public string OrderDetaiStatusContent { get; set; }

        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}