// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelOrderFinal.Models
{
    public partial class Payment
    {
        public Payment()
        {
            OrderDetail = new HashSet<OrderDetail>();
        }

        public int PaymentId { get; set; }
        public string Payment1 { get; set; }
        public decimal? PayDiscount { get; set; }

        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}