// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelOrderFinal.Models
{
    public partial class RoomStyle
    {
        public RoomStyle()
        {
            Room = new HashSet<Room>();
        }

        public string RoomStyleId { get; set; }
        public string RoomStyleName { get; set; }
        public string RoomStyleIdetail { get; set; }

        public virtual ICollection<Room> Room { get; set; }
    }
}