// <
// auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web;


namespace HotelOrderFinal.Models
{
    public partial class RoomMember
    {
        public RoomMember()
        {
            Comment = new HashSet<Comment>();
            DiscountDetail = new HashSet<DiscountDetail>();
            Order = new HashSet<Order>();
        }
        [DisplayName("管理者ID")]
        public string AdminId { get; set; }
        [DisplayName("會員ID")]
        public string MemberId { get; set; }
        [DisplayName("姓名")]
        //[Required(ErrorMessage ="姓名不可以空白")]
        public string MemberName { get; set; }
        [DisplayName("生日")]
        //[Required(ErrorMessage = "生日不可以空白")]
        public DateTime? MemberBirthday { get; set; }
        [DisplayName("性別")]
        //[Required(ErrorMessage = "性別不可以空白")]
        public string MemberGender { get; set; }
        [DisplayName("身分證字號")]
        //[Required(ErrorMessage = "身分證字號不可以空白")]
        public string MemberIdentity { get; set; }

        [DisplayName("電話(註冊時設為帳號)")]

        //[Required(ErrorMessage = "電話不可以空白")]
        public string MemberPhone { get; set; }
        [DisplayName("電子信箱")]
        //[Required(ErrorMessage = "電子信箱不可以空白")]
        [EmailAddress]
        public string MemberEmail { get; set; }
        [DisplayName("照片")]
        public string MemberPhoto { get; set; }
        [DisplayName("密碼")]
        //[Required(ErrorMessage = "密碼不可以空白")]

        public string MemberPassword { get; set; }

        [DisplayName("會員等級")]
        public string MemberLavel { get; set; }
        [DisplayName("累積消費金額")]
        public string MemberOrderTotal { get; set; }

        public virtual RoomAdmin Admin { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<DiscountDetail> DiscountDetail { get; set; }
        public virtual ICollection<Order> Order { get; set; }

        //[Range(typeof(bool), "true", "true", ErrorMessage = "您必須同意會員條款。")]
        public bool AgreeToTerms { get; set; }


    }
}