// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelOrderFinal.Models
{
    public partial class RoomFacility
    {
        public RoomFacility()
        {
            MultipleRoomFacility = new HashSet<MultipleRoomFacility>();
        }

        public int FacilityId { get; set; }
        public string FacilityName { get; set; }
        public string FacilityImage { get; set; }

        public virtual ICollection<MultipleRoomFacility> MultipleRoomFacility { get; set; }
    }
}