// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelOrderFinal.Models
{
    public partial class Room
    {
        public string RoomId { get; set; }
        public string RoomClassId { get; set; }
        public int? HotelId { get; set; }
        public string AdminId { get; set; }

        public virtual RoomAdmin Admin { get; set; }
        public virtual HotelIndustry Hotel { get; set; }
        public virtual RoomClass RoomClass { get; set; }
    }
}