// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;


namespace HotelOrderFinal.Models
{
    public partial class RoomMember
    {
        public RoomMember()
        {
            Comment = new HashSet<Comment>();
            Discount = new HashSet<Discount>();
            Order = new HashSet<Order>();
        }

        public string AdminId { get; set; }
        public string MemberId { get; set; }
        [DisplayName("姓名")]
        [Required(ErrorMessage ="姓名不可空白")]
        public string MemberName { get; set; }
        [DisplayName("生日")]
        [Required(ErrorMessage = "生日不可空白")]
        public DateTime? MemberBirthday { get; set; }
        [DisplayName("性別")]
        [Required(ErrorMessage = "性別不可空白")]
        public string MemberGender { get; set; }
        [DisplayName("身分證字號")]
        [Required(ErrorMessage = "身分證字號不可空白")]
        public string MemberIdentity { get; set; }
        [DisplayName("電話號碼")]
        [Required(ErrorMessage = "電話號碼不可空白")]
        public string MemberPhone { get; set; }
        [DisplayName("電子信箱")]
        [Required(ErrorMessage = "電子信箱不可空白")]
        [EmailAddress(ErrorMessage ="電子信箱格式錯誤")]
        public string MemberEmail { get; set; }
        [DisplayName("個人")]
        public string MemberPhoto { get; set; }
        [DisplayName("密碼")]
        [Required(ErrorMessage = "密碼不可空白")]
        public string MemberPassword { get; set; }
        public string MemberLavel { get; set; }
        public string MemberOrderTotal { get; set; }

        public virtual RoomAdmin Admin { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Discount> Discount { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}