// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelOrderFinal.Models
{
    public partial class RoomImage
    {
        public int RoomImagesId { get; set; }
        public string RoomId { get; set; }
        public string RoomImage1 { get; set; }
        public string RoomImageDetail { get; set; }

        public virtual Room Room { get; set; }
    }
}