// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelOrderFinal.Models
{
    public partial class SpecialRequest
    {
        public SpecialRequest()
        {
            OrderSpecialRequest = new HashSet<OrderSpecialRequest>();
        }

        public int SpecialRequestId { get; set; }
        public string SpecialRequestName { get; set; }

        public virtual ICollection<OrderSpecialRequest> OrderSpecialRequest { get; set; }
    }
}